name: Verify
on:
 - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          bundle
          rake spec
          false

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}
        with:
          sudo: false

